// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDmjnwFMQ2vzaDcquBq2J3DvXRoD3Z6M',
    appId: '1:1054778208258:web:455a9840017d60458bb71b',
    messagingSenderId: '1054778208258',
    projectId: 'fadaly-1023f',
    authDomain: 'fadaly-1023f.firebaseapp.com',
    storageBucket: 'fadaly-1023f.firebasestorage.app',
    measurementId: 'G-EG67KT6B3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-TVO5HfFcag4vnuSR6IT8SsaOjL09nGE',
    appId: '1:1054778208258:android:d6be42ef073f2d848bb71b',
    messagingSenderId: '1054778208258',
    projectId: 'fadaly-1023f',
    storageBucket: 'fadaly-1023f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJC3p_JVwpbY0HmTJlm45Bxvm_veOrig',
    appId: '1:1054778208258:ios:5f42783d5414a64e8bb71b',
    messagingSenderId: '1054778208258',
    projectId: 'fadaly-1023f',
    storageBucket: 'fadaly-1023f.firebasestorage.app',
    iosBundleId: 'com.example.elFadalyGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJC3p_JVwpbY0HmTJlm45Bxvm_veOrig',
    appId: '1:1054778208258:ios:5f42783d5414a64e8bb71b',
    messagingSenderId: '1054778208258',
    projectId: 'fadaly-1023f',
    storageBucket: 'fadaly-1023f.firebasestorage.app',
    iosBundleId: 'com.example.elFadalyGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvDmjnwFMQ2vzaDcquBq2J3DvXRoD3Z6M',
    appId: '1:1054778208258:web:bfdd41f40fc962988bb71b',
    messagingSenderId: '1054778208258',
    projectId: 'fadaly-1023f',
    authDomain: 'fadaly-1023f.firebaseapp.com',
    storageBucket: 'fadaly-1023f.firebasestorage.app',
    measurementId: 'G-CE2YSFK76G',
  );
}
